blobs_path: blobs
blobs_storage: FILESYSTEM
cache: cache
calculate_md5: false
create_image_clip_from_videos: false
dangerous_allow_public_without_auth: "false"
database: stash-go.sqlite
gallery_cover_regex: (poster|cover|folder|board)\.[^\.]+$
generated: generated
host: 0.0.0.0
jwt_secret_key: 88b4a436d06e19ef619bcb12094160431a52668d758ac9d5891f328e136df1d4
no_proxy: localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
nobrowser: false
notifications_enabled: true
parallel_tasks: 1
plugins:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScripts/stable/index.yml
plugins_path: plugins
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scrapers:
    package_sources:
        - localpath: community
          name: Community (stable)
          url: https://stashapp.github.io/CommunityScrapers/stable/index.yml
scrapers_path: scrapers
security_tripwire_accessed_from_public_internet: ""
sequential_scanning: false
session_store_key: ab3054f9fb11ad6e7d6d08c631861b074324f1bac818f5fc04b4473371957dbb
show_one_time_moved_notification: false
sound_on_preview: false
stash: []
theme_color: '#202b33'
ui:
    lastNoteSeen: 20251026
video_file_naming_algorithm: OSHASH
write_image_thumbnails: true
